Improve SHA* marking
gocsaf/csaf pull request #554
Opened 2024-07-25 13:41 UTC by koplas

@JanHoefelmeyer Can you check if all requirements of https://github.com/csaf-poc/csaf_distribution/issues/289#issuecomment-1684906779 are met?

Closes #289

2024-07-25 15:59 UTC, s-l-teichmann reviewed
I am not sure if I like the approach with the extra HEAD requests.

2024-08-09 15:25 UTC, tschmidtb51 commented
> I am not sure if I like the approach with the extra HEAD requests.

@s-l-teichmann I didn't fully check the code. Where was the extra request?

2024-08-10 12:21 UTC, koplas commented
> > I am not sure if I like the approach with the extra HEAD requests.
> 
> @s-l-teichmann I didn't fully check the code. Where was the extra request?

I removed it after the feedback of @s-l-teichmann.

2024-09-30 09:56 UTC, JanHoefelmeyer requested changes
From what I can tell the checker still needs to give out INFO if a SHA is missing in both ROLIE-feed and at all

2024-12-18 16:19 UTC, tschmidtb51 commented
I wonder whether [the comment of just evaluating hashes if they look like hashes](https://github.com/gocsaf/csaf/issues/588#issuecomment-2551271277) is implemented here?

2024-12-19 09:31 UTC, koplas commented
> I wonder whether [the comment of just evaluating hashes if they look like hashes](https://github.com/gocsaf/csaf/issues/588#issuecomment-2551271277) is implemented here?

This part was untouched in this pull request: https://github.com/gocsaf/csaf/blob/d8e903587a8744b51227da17867505da75a44c41/cmd/csaf_checker/processor.go#L785

2025-01-15 12:12 UTC, JanHoefelmeyer submitted a review, later dismissed
LGTM & works

2025-03-10 08:39 UTC, s-l-teichmann approved these changes
LGTM

2025-03-10 08:40 UTC, merged